export const CHANGE_SEARCH_FIELD ='CHANGE_SEARCH_FIELD';

export  const   FETCHING_ROBOTS_PENDING='FETCHING_ROBOTS_PENDING';
export  const   FETCHING_ROBOTS_SUCCESS='FETCHING_ROBOTS_SUCCESS';
export  const   FETCHING_ROBOTS_FAILED='FETCHING_ROBOTS_FAILED';